### ISSUE TITLE
Configure port 5000

### ISSUE THREAD

**Issue by alvarosIGZ** [TykTechnologies/tyk-kubernetes#7]
Hello,
I'm seeing this logs in dashboard (when I press F12 to see the console).

vendors.5d3412e608d096c6bd82.js:424 GET http://MY_IP:5000/socket.io/?chan=ui_notifications.5a981b863797ec0001f393f9&EIO=3&transport=polling&t=M9DG-F4 net::ERR_CONNECTION_REFUSED

I don't see any place where I can change the 5000 port and expose that port through NodePort. 
Is it configurable or at least can I disable and what consquences would have in my Tyk deployment? Best regards

**Comment by buger** [comment]
Port 5000 is used by websockets for real-time notifications, you can update port number using `notifications_listen_port` dashboard config option. 

Thank you.

**Comment by joshblakeley** [comment]
Closing this as Leons reply is correct

**Comment by dijitali** [comment]
To actually fix this though, you'll need also to tell k8s to expose this additional port for real-time notifications.  

It also seems like the [`tyk_analytics.conf`](https://github.com/TykTechnologies/tyk-kubernetes/blob/master/tyk/tyk_analytics.conf) in this repo is out-of-date compared to the example given in the [Tyk Dashboard Configuration Options](https://tyk.io/docs/configure/tyk-dashboard-configuration-options/).

I fixed it by:

1. Adding `"notifications_listen_port": 5000,` to `tyk_analytics.conf`
2. Adding the additional port to `/tyk/deployments/tyk-dashboard.yaml`:
```
ports:
- containerPort: 3000
- containerPort: 5000
```
3. Adding the additional port to `/tyk/services/tyk-dashboard.yaml`:
```
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: listen-port
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: notification-port
```

Updating the configMap with (changes should be picked up after second step):
`kubectl edit configmaps tyk-dashboard-conf --namespace=tyk`

Then update the dashboard deployment and service (ignore the warnings, they're because this tutorial didn't use a declarative kubectl deployment in the first place):
```
kubectl apply -f ./deployments/tyk-dashboard.yaml --namespace tyk
kubectl apply -f ./services/tyk-dashboard.yaml --namespace tyk
```

Then reload the dashboard and notification requests should start working:
![image](https://user-images.githubusercontent.com/4665045/47153506-c33a9c80-d2d7-11e8-9130-198870b146b0.png)

**Comment by talentrydev** [comment]
The fix proposed by @dijitali indeed works, but if you use an ingress, it will fail, because ingress will only accept connections on ports 80/443. So I would need to create a new ingress just for the websocket connections. That's all fine, but you will then also need to expose the "notifications_listen_host" in the configuration.
